name: build

on:
  push:
    branches:
      - main

jobs:
  build-jar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Cache All The Things
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            ~/.clojure
            ~/.cpcache
          key: ${{ runner.os }}-${{ hashFiles('**/deps.edn') }}
      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@master
        with:
          tools-deps: '1.10.3.1087'
      - name: Run tests
        run: clojure -X:test
      - name: Build release
        run: clojure -T:build uber
      - uses: actions/upload-artifact@v2
        with:
          name: jar
          path: target/youtube-channel-data*.jar